package com.korobko.automotiveapp.server.orm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.korobko.automotiveapp.models.EntityRegCard;
import com.korobko.automotiveapp.models.Car;
import com.korobko.automotiveapp.models.Driver;

import com.korobko.automotiveapp.server.orm.EntityRegCardDao;
import com.korobko.automotiveapp.server.orm.CarDao;
import com.korobko.automotiveapp.server.orm.DriverDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entityRegCardDaoConfig;
    private final DaoConfig carDaoConfig;
    private final DaoConfig driverDaoConfig;

    private final EntityRegCardDao entityRegCardDao;
    private final CarDao carDao;
    private final DriverDao driverDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entityRegCardDaoConfig = daoConfigMap.get(EntityRegCardDao.class).clone();
        entityRegCardDaoConfig.initIdentityScope(type);

        carDaoConfig = daoConfigMap.get(CarDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        driverDaoConfig = daoConfigMap.get(DriverDao.class).clone();
        driverDaoConfig.initIdentityScope(type);

        entityRegCardDao = new EntityRegCardDao(entityRegCardDaoConfig, this);
        carDao = new CarDao(carDaoConfig, this);
        driverDao = new DriverDao(driverDaoConfig, this);

        registerDao(EntityRegCard.class, entityRegCardDao);
        registerDao(Car.class, carDao);
        registerDao(Driver.class, driverDao);
    }
    
    public void clear() {
        entityRegCardDaoConfig.clearIdentityScope();
        carDaoConfig.clearIdentityScope();
        driverDaoConfig.clearIdentityScope();
    }

    public EntityRegCardDao getEntityRegCardDao() {
        return entityRegCardDao;
    }

    public CarDao getCarDao() {
        return carDao;
    }

    public DriverDao getDriverDao() {
        return driverDao;
    }

}
